cabal-version:       2.2
name:                holbert
version:             0.6
synopsis:            An interactive proof assistant
category:            Web
license:             BSD-3-Clause
license-file:        LICENSE
build-type:          Simple

flag mixfix
  description: Enable mixfix operator
  default:     False

common shared
  other-modules:
    StringRep
    Prop
    ProofTree
    Terms
    Unification
    Editor
    Rule
    Heading
    SyntaxDecl
    Paragraph
    Controller
    Item
    DisplayOptions
    ImportExport
    View.Editor
    View.Term
    View.Utils
    View.ProofTree
    View.Prop
    View.Paragraph
    View.Heading
    View.SyntaxDecl
    View.Rule
    View.Item
    Parse.Parser
    Parse.Printer
  ghcjs-options:
    -dedupe
    -Wall
  build-depends:       base, ghcjs-base == 0.2.1.0, aeson, hashable==1.3.5.0, text, miso, mtl, containers==0.6.8, optics-core, Earley, jsaddle == 0.9.8.2, unordered-containers==0.2.19.1, array, hspec
  build-tools-depends:
    happy
  default-language:    Haskell2010

executable app
  import: shared
  --if flag(mixfix)
  --  cpp-options: -DMIXFIX
  main-is:             Main.hs

executable test
  import: shared
  --if flag(mixfix)
  --  cpp-options: -DMIXFIX
  main-is:             Spec.hs
